//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistique.Valida.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendeeType
    {
        public AttendeeType()
        {
            this.Users = new HashSet<User>();
            this.Participants = new HashSet<Participant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
    }
}
