//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistique.Valida.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Projects = new HashSet<Project>();
            this.Requirements = new HashSet<Requirement>();
            this.Defects = new HashSet<Defect>();
        }
    
        public int Id { get; set; }
        public string IDCode { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<Defect> Defects { get; set; }
    }
}
