//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistique.Valida.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect
    {
        public Defect()
        {
            this.DescriptionFiles = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public string Abstract { get; set; }
        public int SlideNo { get; set; }
        public int TaskNo { get; set; }
        public string SourceText { get; set; }
        public string TargetText { get; set; }
        public string Description { get; set; }
        public bool ContextRequired { get; set; }
        public string SuggestionText { get; set; }
        public string LinguistCorrection { get; set; }
        public string CommentQA { get; set; }
        public int ProjectId { get; set; }
        public int BrandId { get; set; }
        public int LanguageId { get; set; }
        public int ApplicationEnggUserId { get; set; }
        public int LinguistUserId { get; set; }
        public int ApplicationId { get; set; }
        public int SeverityId { get; set; }
        public int CategoryId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Language Language { get; set; }
        public virtual User ApplicationEngg { get; set; }
        public virtual User Linguist { get; set; }
        public virtual Application Application { get; set; }
        public virtual ICollection<File> DescriptionFiles { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
    }
}
