//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistique.Valida.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Requirements = new HashSet<Requirement>();
            this.Defects = new HashSet<Defect>();
            this.Brands = new HashSet<Brand>();
            this.Languages = new HashSet<Language>();
            this.Steamers = new HashSet<User>();
            this.ITers = new HashSet<User>();
            this.Partners = new HashSet<User>();
            this.Participants = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IDCode { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<Defect> Defects { get; set; }
        public virtual User Manager { get; set; }
        public virtual ICollection<Brand> Brands { get; set; }
        public virtual ICollection<Language> Languages { get; set; }
        public virtual ICollection<User> Steamers { get; set; }
        public virtual ICollection<User> ITers { get; set; }
        public virtual ICollection<User> Partners { get; set; }
        public virtual Release Release { get; set; }
        public virtual ICollection<User> Participants { get; set; }
    }
}
