//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistique.Valida.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Requirements = new HashSet<Requirement>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IDCode { get; set; }
    
        public virtual ICollection<Requirement> Requirements { get; set; }
    }
}
