//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linguistique.Valida.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ProjectsManager = new HashSet<Project>();
            this.ProjectsSteamers = new HashSet<Project>();
            this.ProjectsITers = new HashSet<Project>();
            this.ProjectsPartners = new HashSet<Project>();
            this.ProjectsParticipants = new HashSet<Project>();
            this.RequirementsTLead = new HashSet<Requirement>();
            this.RequirementsResponsible = new HashSet<Requirement>();
            this.DefectsApplicationEngg = new HashSet<Defect>();
            this.DefectsLinguist = new HashSet<Defect>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IDCode { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Project> ProjectsManager { get; set; }
        public virtual ICollection<Project> ProjectsSteamers { get; set; }
        public virtual ICollection<Project> ProjectsITers { get; set; }
        public virtual ICollection<Project> ProjectsPartners { get; set; }
        public virtual ICollection<Project> ProjectsParticipants { get; set; }
        public virtual ICollection<Requirement> RequirementsTLead { get; set; }
        public virtual ICollection<Requirement> RequirementsResponsible { get; set; }
        public virtual ICollection<Defect> DefectsApplicationEngg { get; set; }
        public virtual ICollection<Defect> DefectsLinguist { get; set; }
    }
}
